version: '3.8'

services:
  # Ubuntu版本（默认，更好的兼容性）
  fingerprint-chromium:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FC_VERSION: "136.0.7103.113"
    container_name: fingerprint-chromium-ubuntu
    ports:
      - "9222:9222"  # Chrome DevTools Protocol
      - "6081:6081"  # noVNC web interface
      - "5901:5901"  # VNC direct access
    environment:
      - VNC_PASSWORD=changeme
      - FINGERPRINT_SEED=2025
      - FINGERPRINT_PLATFORM=linux
      - FINGERPRINT_BRAND=Chrome
      - BROWSER_LANG=zh-CN
      - ACCEPT_LANG=zh-CN,zh
      - TIMEZONE=Asia/Shanghai
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      # - PROXY_SERVER=http://proxy:8080
      # - CHROME_EXTRA_ARGS=--disable-web-security
    volumes:
      - ./chrome-data:/home/browser/.chrome-data
      - ./chrome-profiles:/home/browser/.chrome-profiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:9222/json/version"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Alpine版本（更小的镜像体积）
  fingerprint-chromium-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        FC_VERSION: "136.0.7103.113"
    container_name: fingerprint-chromium-alpine
    ports:
      - "9223:9222"  # Chrome DevTools Protocol (不同端口避免冲突)
      - "6082:6081"  # noVNC web interface
      - "5902:5901"  # VNC direct access
    environment:
      - VNC_PASSWORD=changeme
      - FINGERPRINT_SEED=2025
      - FINGERPRINT_PLATFORM=linux
      - FINGERPRINT_BRAND=Chrome
      - BROWSER_LANG=zh-CN
      - ACCEPT_LANG=zh-CN,zh
      - TIMEZONE=Asia/Shanghai
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    volumes:
      - ./chrome-data-alpine:/home/browser/.chrome-data
      - ./chrome-profiles-alpine:/home/browser/.chrome-profiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:9222/json/version"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
