version: '3.8'

services:
  # 新版本 fingerprint-chromium（基于webvnc）
  fingerprint-chromium-new:
    build:
      context: .
      dockerfile: Dockerfile.new
      args:
        FC_VERSION: "136.0.7103.113"
    container_name: fingerprint-chromium-new
    ports:
      - "9222:9222"  # Chrome DevTools Protocol
      - "6081:6081"  # noVNC web interface
      - "5901:5901"  # VNC direct access
    environment:
      - VNC_PASSWORD=changeme
      - FINGERPRINT_SEED=2025
      - FINGERPRINT_PLATFORM=linux
      - FINGERPRINT_BRAND=Chrome
      - BROWSER_LANG=zh-CN
      - ACCEPT_LANG=zh-CN,zh
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK_SET=022
      # - PROXY_SERVER=http://proxy:8080
      # - CHROME_EXTRA_ARGS=--disable-web-security
    volumes:
      - ./chrome-data-new:/home/browser/.chrome-data
      - ./chrome-profiles-new:/home/browser/.chrome-profiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:9222/json/version"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 测试用的简化版本（无VNC，仅API）
  fingerprint-chromium-headless:
    build:
      context: .
      dockerfile: Dockerfile.new
      args:
        FC_VERSION: "136.0.7103.113"
    container_name: fingerprint-chromium-headless
    ports:
      - "9223:9222"  # Chrome DevTools Protocol (不同端口避免冲突)
    environment:
      - FINGERPRINT_SEED=3000
      - FINGERPRINT_PLATFORM=linux
      - FINGERPRINT_BRAND=Chrome
      - BROWSER_LANG=en-US
      - ACCEPT_LANG=en-US,en
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - CHROME_EXTRA_ARGS=--headless --disable-gpu
    volumes:
      - ./chrome-data-headless:/home/browser/.chrome-data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:9222/json/version"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
